# Generated by Django 3.0.5 on 2021-08-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210823_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='trans',
            field=models.CharField(max_length=32, verbose_name='Перевод'),
        ),
    ]
