# Generated by Django 3.0.5 on 2021-08-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210823_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('anons', models.TextField(verbose_name='Анонс')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
